version: '3.8'

services:
  logging-server:
    build: .
    container_name: logging_server
    environment:
      - RABBITMQ_HOST=rabbitmq
      - GRPC_PORT=50051
    ports:
      - "50051:50051"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"