version: "3.9"

services:
  logging:
    build: .
    container_name: logging-service
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq/
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8002", "--reload"]
    ports:
      - "8002:8002"  # Logging-Service API Port
    volumes:
      - ./logs:/app/logs
      - ./app:/app/app
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    name: integrationproject_backend
    external: true