version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ Standard Port
      - "15672:15672" # Management Interface
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  logging:
    build: .
    container_name: logging-service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq/
    command: ["python", "event_logger.py"]
    volumes:
      - ./logs:/app/logs
      - ./app:/app/app    # Für Hot-Reloading im Entwicklungsmodus
    ports:
      - "8002:8002"
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  backend:
    name: integrationproject_backend
    external: true

volumes:
  rabbitmq_data: