version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # Port für RabbitMQ Verbindungen (AMQP)
      - "15672:15672"    # Port für das RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend

  ecommerce:
    build: ../ecommerce
    container_name: ecommerce_service
    depends_on:
      - rabbitmq
      - logging
    networks:
      - backend

  erp:
    build: ../erp
    container_name: erp_service
    depends_on:
      - rabbitmq
      - logging
    networks:
      - backend

  crm:
    build: ../crm
    container_name: crm_service
    depends_on:
      - rabbitmq
      - logging
    networks:
      - backend
      
  logging:
    build: ../logging
    container_name: logging_service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq/
    volumes:
      - ../logging/logs:/app/logs
    ports:
      - "8002:8002"  # Logging-Service API Port
    depends_on:
      - rabbitmq
    networks:
      - backend

  erp2:
    build: ../erp
    container_name: erp2_service
    depends_on:
      - rabbitmq
    networks:
      - backend
    ports:
      - "50052:50052"

networks:
  backend:
    driver: bridge
