# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import erp_service_pb2 as protos_dot_erp__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/erp_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ERPServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessOrder = channel.unary_unary(
                '/erp2.protos.ERPService/ProcessOrder',
                request_serializer=protos_dot_erp__service__pb2.OrderRequest.SerializeToString,
                response_deserializer=protos_dot_erp__service__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.GetProductStock = channel.unary_unary(
                '/erp2.protos.ERPService/GetProductStock',
                request_serializer=protos_dot_erp__service__pb2.ProductRequest.SerializeToString,
                response_deserializer=protos_dot_erp__service__pb2.ProductResponse.FromString,
                _registered_method=True)


class ERPServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessOrder(self, request, context):
        """Process incoming orders and return shipping information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProductStock(self, request, context):
        """Get product stock information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ERPServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessOrder,
                    request_deserializer=protos_dot_erp__service__pb2.OrderRequest.FromString,
                    response_serializer=protos_dot_erp__service__pb2.OrderResponse.SerializeToString,
            ),
            'GetProductStock': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductStock,
                    request_deserializer=protos_dot_erp__service__pb2.ProductRequest.FromString,
                    response_serializer=protos_dot_erp__service__pb2.ProductResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'erp2.protos.ERPService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('erp2.protos.ERPService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ERPService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/erp2.protos.ERPService/ProcessOrder',
            protos_dot_erp__service__pb2.OrderRequest.SerializeToString,
            protos_dot_erp__service__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProductStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/erp2.protos.ERPService/GetProductStock',
            protos_dot_erp__service__pb2.ProductRequest.SerializeToString,
            protos_dot_erp__service__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
