# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/erp_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/erp_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18protos/erp_service.proto\x12\x0b\x65rp2.protos\"[\n\x0cOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x02 \x01(\t\x12\x12\n\nproduct_id\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\"N\n\rOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x15\n\rshipping_date\x18\x02 \x01(\t\x12\x14\n\x0corder_status\x18\x03 \x01(\t\"$\n\x0eProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\"f\n\x0fProductResponse\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x14\n\x0cproduct_name\x18\x02 \x01(\t\x12\x13\n\x0bstock_level\x18\x03 \x01(\x05\x12\x14\n\x0cretail_price\x18\x04 \x01(\x01\x32\xa1\x01\n\nERPService\x12\x45\n\x0cProcessOrder\x12\x19.erp2.protos.OrderRequest\x1a\x1a.erp2.protos.OrderResponse\x12L\n\x0fGetProductStock\x12\x1b.erp2.protos.ProductRequest\x1a\x1c.erp2.protos.ProductResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.erp_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERREQUEST']._serialized_start=41
  _globals['_ORDERREQUEST']._serialized_end=132
  _globals['_ORDERRESPONSE']._serialized_start=134
  _globals['_ORDERRESPONSE']._serialized_end=212
  _globals['_PRODUCTREQUEST']._serialized_start=214
  _globals['_PRODUCTREQUEST']._serialized_end=250
  _globals['_PRODUCTRESPONSE']._serialized_start=252
  _globals['_PRODUCTRESPONSE']._serialized_end=354
  _globals['_ERPSERVICE']._serialized_start=357
  _globals['_ERPSERVICE']._serialized_end=518
# @@protoc_insertion_point(module_scope)
